/** Studio chrome is deliberately independent of the trace canvas theme. */
export const studioStyles = String.raw`
:root{color-scheme:light;--ink:#22312f;--muted:#677572;--line:#dfe5e1;--accent:#216b54;--paper:#fff;--wash:#f6f8f6}
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:var(--wash);color:var(--ink);font:14px/1.45 "Segoe UI",system-ui,sans-serif}
button,input,select,summary{font:inherit}button,input,select{min-height:32px;border:1px solid var(--line);border-radius:6px;background:white;color:inherit;padding:5px 9px}button,summary{cursor:pointer}button:hover{background:#edf3ef}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible,a:focus-visible{outline:2px solid var(--accent);outline-offset:2px}[hidden]{display:none!important}
.studio{display:grid;grid-template-columns:320px minmax(0,1fr);height:100%}.rail{min-height:0;display:flex;flex-direction:column;border-right:1px solid var(--line);background:var(--paper)}.rail-head{padding:20px 16px 12px;flex:none}.brand{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand strong{font-size:16px;letter-spacing:-.4px}.local{font-size:11px;color:var(--accent);background:#edf6ef;padding:3px 7px;border-radius:20px}.nav-tabs,.quick-views{display:flex;gap:4px;margin-bottom:12px}.nav-tabs button{flex:1;border:0;background:transparent;font-weight:600}.nav-tabs button[aria-pressed=true]{background:#eaf1ed;color:var(--accent)}#history-filters{display:grid;gap:10px} .search-line{display:flex;gap:6px}.search-line input{width:100%;min-width:0;background:var(--wash)}.quick-views{margin:0;flex-wrap:wrap}.quick-views button{border:0;font-size:12px;padding:4px 8px}.quick-views button[aria-pressed=true]{background:var(--ink);color:white}.filters summary{font-size:12px;color:var(--muted)}.filter-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:10px}.filter-grid label{display:grid;gap:3px;font-size:11px;color:var(--muted)}input,select{min-width:0;max-width:100%}.chips{display:flex;gap:4px;flex-wrap:wrap}.chips:empty{display:none}.chips button{font-size:11px;min-height:26px;padding:2px 6px;background:var(--wash)}
.history-scroll{overflow:auto;min-height:0;flex:1;padding:0 8px}.date-group{font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted);margin:16px 10px 7px}.session-row{position:relative;border-radius:8px;margin:2px 0}.session-row:has([aria-current=true]){background:#eaf2ec;box-shadow:inset 3px 0 var(--accent)}.session{display:block;width:100%;text-align:left;border:0;background:transparent;padding:11px 36px 11px 12px;min-height:68px}.session:hover{background:#f0f4f1}.session-title{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;font-weight:600;overflow-wrap:anywhere}.session-meta{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px;margin-top:4px}.status-dot{font-size:12px}.status-failed,.status-interrupted{color:#ac492d}.status-running{color:#216b54}.row-menu{position:absolute;right:4px;top:10px}.row-menu summary{list-style:none;padding:3px 8px;min-height:28px;border-radius:4px;color:var(--muted)}.row-menu summary::-webkit-details-marker{display:none}.row-menu[open]{z-index:5}.row-menu[open] summary{background:white}.actions{position:absolute;right:0;top:30px;width:235px;padding:8px;background:white;box-shadow:0 8px 30px #243c3526;border:1px solid var(--line);border-radius:8px;display:grid;gap:4px}.actions button{text-align:left;border:0}.actions button[aria-pressed=true]{background:#eaf2ec}.actions input{width:100%}.actions .danger{color:#a33d2c}.rail-footer{padding:10px 16px;border-top:1px solid var(--line);font-size:11px;color:var(--muted)}#notice{margin:0 0 6px;min-height:16px}.paging{display:flex;justify-content:space-between;align-items:center}.paging button{font-size:12px}.empty{padding:24px 12px;color:var(--muted)}
.workspace{display:flex;flex-direction:column;min-width:0;min-height:0}.run-header{background:white;border-bottom:1px solid var(--line);padding:16px 24px}.run-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.run-heading h1{font-size:19px;line-height:1.3;letter-spacing:-.4px;margin:0;overflow-wrap:anywhere}.run-heading p{font-size:12px;color:var(--muted);margin:6px 0 0}.run-tools{display:flex;gap:6px;flex:none}.workspace-tabs{display:flex;gap:18px;margin-top:15px}.workspace-tabs button{border:0;border-radius:0;background:none;color:var(--muted);padding:5px 0}.workspace-tabs button[aria-pressed=true]{color:var(--accent);box-shadow:0 2px var(--accent);font-weight:600}#baseline{font-size:12px;color:var(--muted);margin:8px 0 0}.workspace-body{position:relative;flex:1;min-height:0;display:flex;flex-direction:column}agent-think-map{display:flex;flex:1;min-width:0;min-height:0;height:100%}.investigation{padding:24px;overflow:auto;flex:1}.investigation h2{font-size:18px;margin:0 0 8px}.investigation h3{font-size:14px}.investigation p{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:18px 0}.metric,.evidence-card{padding:16px;border:1px solid var(--line);background:white;border-radius:10px}.metric small{display:block;color:var(--muted)}.metric strong{display:block;font-size:20px;margin-top:5px}.evidence-card{margin:10px 0}.evidence-card pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 Consolas,monospace;max-height:280px;overflow:auto}.evidence-card button{margin:4px 6px 0 0}.agent-row{margin:8px 0;padding:12px;border-left:2px solid var(--line);background:white}.agent-row button{margin-right:6px}.agent-row p{margin:5px 0;font-size:12px}.problem-row{display:block;text-align:left;width:100%;padding:14px 12px;margin:4px 0;background:white;border:0;border-radius:8px}.problem-row strong,.problem-row small{display:block}.problem-row small{margin-top:5px;color:var(--muted)}.problem-row[aria-current=true]{background:#eaf2ec}.back-link{margin-bottom:16px}.muted{color:var(--muted);font-size:12px}
.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
@media(max-width:900px){.studio{grid-template-columns:270px minmax(0,1fr)}.run-header{padding:14px}.run-heading{flex-direction:column}.diff-body{grid-template-columns:1fr 1fr}.change-rail{grid-column:1/-1;flex-direction:row;overflow:auto}.investigation{padding:16px}}
@media(max-width:640px){html,body{overflow:auto}.studio{display:flex;flex-direction:column;height:auto;min-height:100%}.rail{height:380px;border-right:0;border-bottom:1px solid var(--line)}.rail-head{padding:12px}.brand{margin-bottom:8px}.nav-tabs{margin-bottom:8px}.workspace{height:80vh;min-height:550px}.run-heading h1{font-size:17px}.diff-body{grid-template-columns:1fr}.change-rail{grid-column:auto}}
.workspace .atc-root{--atc-ink:#22312f;--atc-vellum:#f4f7f4;--atc-card:#fff;--atc-graphite:#677572;--atc-tape:#e5ece6;--atc-rule:#dfe5e1;--atc-font-display:"Segoe UI",system-ui,sans-serif;--atc-font-body:"Segoe UI",system-ui,sans-serif;background:var(--atc-vellum)}
.studio{grid-template-columns:var(--history-width,320px) 8px minmax(0,1fr)}
.studio[data-sidebar-collapsed]{grid-template-columns:minmax(0,1fr)}
.rail{min-width:0;border-right:0}.brand{gap:8px}.brand strong{flex:1}
#collapse-sidebar{font-size:23px;line-height:1;padding:0 7px;min-width:32px;border:0}
#expand-sidebar{flex:none;white-space:nowrap}.run-heading>div{min-width:0;flex:1}
.sidebar-resizer{position:relative;cursor:col-resize;touch-action:none;background:var(--wash);border-left:1px solid var(--line);border-right:1px solid var(--line)}
.sidebar-resizer::after{content:"";position:absolute;left:2px;top:calc(50% - 18px);height:36px;width:2px;border-radius:2px;background:#aab9b0}
.sidebar-resizer:hover,.sidebar-resizer:focus-visible,.studio[data-sidebar-dragging] .sidebar-resizer{background:#c7ded0;outline:0}
.sidebar-resizer:focus-visible{box-shadow:inset 0 0 0 2px var(--accent)}
.studio[data-sidebar-dragging]{cursor:col-resize;user-select:none}.studio[data-sidebar-dragging] .workspace{pointer-events:none}
@media(max-width:640px){.sidebar-resizer{display:none}.studio[data-sidebar-collapsed] .workspace{height:100vh}.run-heading{flex-direction:row}}
/* Contain each pane at every zoom level. Expanded filters scroll within the header. */
.rail{overflow:hidden;isolation:isolate}
.rail-head{flex:0 1 auto;min-height:0;max-height:60%;overflow:auto;overscroll-behavior:contain;scrollbar-gutter:stable}
.history-scroll{flex:1 1 120px;overscroll-behavior:contain;scrollbar-gutter:stable}
.rail-footer{flex:0 0 auto;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;background:var(--paper);position:relative}
.rail-footer #notice{margin:0;min-height:0;flex:1 1 100px;line-height:1.5;overflow-wrap:anywhere}
.paging{flex:0 0 auto}.paging button{white-space:nowrap}
.filter-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.filter-grid label{min-width:0}
.run-header{flex:0 0 auto}.run-heading p{overflow-wrap:anywhere}
.workspace-tabs{flex-wrap:wrap}.chips button{max-width:100%;overflow-wrap:anywhere;text-align:left}
@media(max-width:640px){
  html,body{overflow:hidden}
  .studio{height:100dvh;min-height:0;position:relative;overflow:hidden}
  .rail{position:absolute;inset:0 auto 0 0;width:min(320px,calc(100% - 56px));min-height:0;height:100dvh;z-index:2;border-right:1px solid var(--line);box-shadow:8px 0 28px #22312f24}
  .rail-head{max-height:60%}
  /* Isolate canvas layers beneath the drawer while keeping its dimensions stable. */
  .studio .workspace{position:relative;isolation:isolate;z-index:0;flex:1;width:100%;height:100dvh;min-height:0}
  .run-heading{flex-wrap:wrap}
}
`;
